2015/04/22 12:31:25 [error] [system.db.CDbCommand] Error in preparing SQL: SELECT COUNT(*) FROM AuthItem
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:31:25 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: CDbCommand failed to prepare the SQL statement: SQLSTATE[HY000]: General error: 1 no such table: AuthItem. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:31:29 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:32:11 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:34:35 [error] [exception.CDbException] exception 'CDbException' with message 'The table "USER" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:34:44 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:37:33 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:37:41 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:41:19 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lastvisit' in 'field list'. The SQL statement executed was: SELECT id, username, email, createtime, lastvisit, superuser, status, password, activkey FROM `users` `t` WHERE `t`.`username`=:yp0 LIMIT 1.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
in C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php (19)
2015/04/22 12:41:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'lastvisit' in 'field list'. The SQL statement executed was: SELECT id, username, email, createtime, lastvisit, superuser, status, password, activkey FROM `users` `t` WHERE `t`.`username`=:yp0 LIMIT 1' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1356): CDbCommand->queryRow()
#2 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1524): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->findByAttributes(Array)
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:44:01 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (331)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php (21)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (57)
2015/04/22 12:44:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php(331): CDbAuthManager->getAuthAssignments('1')
#3 C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('1')
#4 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(246): RWebUser->afterLogin(false)
#5 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(57): CWebUser->login(Object(UserIdentity), 2592000)
#6 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#7 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#8 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#9 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#16 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:47:49 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:24 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:24 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:25 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:25 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:26 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:26 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:27 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:27 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:27 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:27 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:30 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:30 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:32 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:37 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:37 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:41 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:41 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:52 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:52 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:52:54 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:53:08 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `authassignment`
WHERE userid=:userid.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (331)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php (21)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (57)
2015/04/22 12:53:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `authassignment`
WHERE userid=:userid' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php(331): CDbAuthManager->getAuthAssignments('1')
#3 C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('1')
#4 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(246): RWebUser->afterLogin(false)
#5 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(57): CWebUser->login(Object(UserIdentity), 2592000)
#6 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#7 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#8 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#9 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#16 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 12:59:47 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:59:48 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 12:59:48 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:01:01 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:01:01 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:01:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "users".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/footprint/index.php?r=users
---
2015/04/22 13:01:22 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM authitem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:01:22 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE authitem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:05:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "rights".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/footprint/index.php?r=rights
HTTP_REFERER=http://localhost/footprint/index.php
---
2015/04/22 13:05:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/login".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=site/index
---
2015/04/22 13:18:05 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:18:05 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:19:06 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:19:06 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:23:24 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\models\LoginForm.php (52)
2015/04/22 13:23:24 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\htdocs\footprint\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=site/login
HTTP_REFERER=http://localhost/footprint/index.php?r=site/login
---
2015/04/22 13:23:33 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:23:36 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:23:36 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:26:03 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:26:03 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:26:29 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:26:29 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:26:39 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\models\LoginForm.php (52)
2015/04/22 13:26:39 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\htdocs\footprint\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=site/login
HTTP_REFERER=http://localhost/footprint/index.php?r=site/login
---
2015/04/22 13:26:49 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:26:52 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:26:52 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:27:18 [error] [exception.CException] exception 'CException' with message 'Alias "user.UserModule" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\yii\framework\YiiBase.php:323
Stack trace:
#0 C:\xampp\htdocs\yii\framework\YiiBase.php(196): YiiBase::import('user.UserModule', true)
#1 C:\xampp\htdocs\yii\framework\base\CModule.php(282): YiiBase::createComponent('user.UserModule', 'user', NULL, Array)
#2 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(337): CModule->getModule('user')
#3 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(276): CWebApplication->createController('user/login')
#4 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#5 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#6 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#7 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:29:18 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:29:18 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:29:35 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:29:35 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:29:43 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\models\LoginForm.php (52)
2015/04/22 13:29:43 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\htdocs\footprint\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=site/login
HTTP_REFERER=http://localhost/footprint/index.php?r=site/login
---
2015/04/22 13:30:56 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\models\LoginForm.php (52)
2015/04/22 13:30:56 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\htdocs\footprint\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=site/login
HTTP_REFERER=http://localhost/footprint/index.php?r=site/login
---
2015/04/22 13:32:21 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\models\LoginForm.php (52)
2015/04/22 13:32:21 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#8 C:\xampp\htdocs\footprint\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=site/login
HTTP_REFERER=http://localhost/footprint/index.php?r=site/login
---
2015/04/22 13:32:33 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:32:36 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `users`.
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php (27)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (52)
2015/04/22 13:32:36 [error] [exception.CDbException] exception 'CDbException' with message 'The table "users" for active record class "User" cannot be found in the database.' in C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2385
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 C:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(212): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): CActiveRecord->__call('notsafe', Array)
#3 C:\xampp\htdocs\footprint\protected\modules\user\components\UserIdentity.php(27): User->notsafe()
#4 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(52): UserIdentity->authenticate()
#5 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#6 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#7 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#8 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#9 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#15 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#16 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:34:06 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (331)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php (21)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (57)
2015/04/22 13:34:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php(331): CDbAuthManager->getAuthAssignments('1')
#3 C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('1')
#4 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(246): RWebUser->afterLogin(false)
#5 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(57): CWebUser->login(Object(UserIdentity), 2592000)
#6 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#7 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#8 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#9 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#16 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:34:17 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:34:17 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:34:25 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:34:25 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:34:57 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:35:00 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (331)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php (21)
in C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php (57)
2015/04/22 13:35:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authassignment' doesn't exist. The SQL statement executed was: SELECT *
FROM `AuthAssignment`
WHERE userid=:userid' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(337): CDbCommand->queryAll()
#2 C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php(331): CDbAuthManager->getAuthAssignments('1')
#3 C:\xampp\htdocs\footprint\protected\modules\rights\components\RWebUser.php(21): RAuthorizer->isSuperuser('1')
#4 C:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(246): RWebUser->afterLogin(false)
#5 C:\xampp\htdocs\footprint\protected\modules\user\models\UserLogin.php(57): CWebUser->login(Object(UserIdentity), 2592000)
#6 C:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): UserLogin->authenticate('password', Array)
#7 C:\xampp\htdocs\yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(UserLogin), 'password')
#8 C:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(UserLogin), NULL)
#9 C:\xampp\htdocs\footprint\protected\modules\user\controllers\LoginController.php(19): CModel->validate()
#10 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): LoginController->actionLogin()
#11 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#15 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('user/login')
#16 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#17 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/footprint/index.php?r=user/login
HTTP_REFERER=http://localhost/footprint/index.php?r=user/login
---
2015/04/22 13:37:22 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:37:27 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (215)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:37:27 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'type=InnoDB' at line 8. The SQL statement executed was: CREATE TABLE AuthItem (
					name varchar(64) not null,
					type integer not null,
					description text,
					bizrule text,
					data text,
					primary key (name)
					) type=InnoDB.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (96)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (92)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 13:38:12 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT name,t1.type,description,t1.bizrule,t1.data,weight
					FROM AuthItem t1
					LEFT JOIN AuthAssignment t2 ON name=t2.itemname
					LEFT JOIN Rights t3 ON name=t3.itemname
					WHERE t1.type=:type AND userid=:userid
					ORDER BY t1.type DESC, weight ASC.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RDbAuthManager.php (166)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (101)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (290)
2015/04/22 13:38:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT name,t1.type,description,t1.bizrule,t1.data,weight
					FROM AuthItem t1
					LEFT JOIN AuthAssignment t2 ON name=t2.itemname
					LEFT JOIN Rights t3 ON name=t3.itemname
					WHERE t1.type=:type AND userid=:userid
					ORDER BY t1.type DESC, weight ASC' in C:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\yii\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\footprint\protected\modules\rights\components\RDbAuthManager.php(166): CDbCommand->queryAll()
#2 C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php(101): RDbAuthManager->getAuthItems(2, '1', true)
#3 C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php(290): RAuthorizer->getAuthItems(2, '1')
#4 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(1144): AssignmentController->accessRules()
#6 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#7 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#12 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/footprint/index.php?r=rights
---
2015/04/22 13:39:22 [error] [php] Undefined variable: permissions (C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php:354)
Stack trace:
#0 C:\xampp\htdocs\footprint\protected\modules\rights\components\dataproviders\RPermissionDataProvider.php(36): RPermissionDataProvider->init()
#1 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\AuthItemController.php(77): RPermissionDataProvider->__construct()
#2 C:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): AuthItemController->actionPermissions()
#3 C:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): AuthItemController->runAction()
#5 C:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 C:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#7 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): AuthItemController->filterAccessControl()
#8 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#9 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 C:\xampp\htdocs\yii\framework\web\CController.php(265): AuthItemController->runActionWithFilters()
#11 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): AuthItemController->run()
#12 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\footprint\index.php(13): CWebApplication->run()
REQUEST_URI=/footprint/index.php?r=rights/authItem/permissions
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php (354)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\dataproviders\RPermissionDataProvider.php (84)
in C:\xampp\htdocs\footprint\protected\modules\rights\components\dataproviders\RPermissionDataProvider.php (49)
2015/04/22 13:41:24 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'There must be at least one superuser!' in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php:305
Stack trace:
#0 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php(61): RAuthorizer->getSuperusers()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(1144): InstallController->accessRules()
#2 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/install')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/footprint/index.php?r=rights/install
---
2015/04/22 13:41:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'There must be at least one superuser!' in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php:305
Stack trace:
#0 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php(61): RAuthorizer->getSuperusers()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(1144): InstallController->accessRules()
#2 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/install')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/footprint/index.php?r=rights/install
---
2015/04/22 13:42:18 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'There must be at least one superuser!' in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php:305
Stack trace:
#0 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php(61): RAuthorizer->getSuperusers()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(1144): InstallController->accessRules()
#2 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/install')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/footprint/index.php?r=rights/install
---
2015/04/22 13:42:28 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'There must be at least one superuser!' in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php:305
Stack trace:
#0 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php(61): RAuthorizer->getSuperusers()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(1144): InstallController->accessRules()
#2 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights/install')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/footprint/index.php?r=rights/install
---
2015/04/22 13:42:54 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'There must be at least one superuser!' in C:\xampp\htdocs\footprint\protected\modules\rights\components\RAuthorizer.php:305
Stack trace:
#0 C:\xampp\htdocs\footprint\protected\modules\rights\controllers\AssignmentController.php(51): RAuthorizer->getSuperusers()
#1 C:\xampp\htdocs\yii\framework\web\CController.php(1144): AssignmentController->accessRules()
#2 C:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#3 C:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#5 C:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#7 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#8 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/footprint/index.php?r=rights
---
2015/04/22 13:43:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "rights".' in C:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('rights')
#1 C:\xampp\htdocs\yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\footprint\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/footprint/index.php?r=rights
---
2015/04/22 13:50:20 [error] [system.db.CDbCommand] CDbCommand::fetchColumn() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pegada_energetica.authitem' doesn't exist. The SQL statement executed was: SELECT COUNT(*) FROM AuthItem.
in C:\xampp\htdocs\footprint\protected\modules\rights\components\RInstaller.php (180)
in C:\xampp\htdocs\footprint\protected\modules\rights\controllers\InstallController.php (43)
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:06 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:11 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:25 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:28 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:37 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:39 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:49 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:47:50 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:05 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:06 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:18 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:20 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:30 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:31 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:38 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
2015/04/22 14:48:39 [warning] [application] Failed to set unsafe attribute "layout" of "AweCrudCode".
in C:\xampp\htdocs\footprint\index.php (13)
